update dotfiles

diff --git a/.local/bin/ifinstalled b/.local/bin/ifinstalled
--- a/.local/bin/ifinstalled
+++ b/.local/bin/ifinstalled
@@ -6,6 +6,8 @@
 
 for x in "$@"; do
 	if ! which "$x" >/dev/null 2>&1 && ! pacman -Qq "$x" >/dev/null 2>&1; then
-		notify-send "📦 $x" "must be installed for this function." && exit 1 ;
+		echo "Error: $x must be installed for this function." >&2
+		notify-send -u critical "📦 $x" "$x must be installed for this function."
+		exit 1
 	fi
 done
